export interface GM11Result {
    a: number;
    b: number;
    predictedValues: number[];
    forecast: number[];
}

/**
 * Grey Model GM(1,1) Implementation
 * @param data Array of numbers representing the original time series data (e.g., closing prices). Must have at least 4 data points.
 * @param forecastSteps Number of future steps to predict.
 * @returns GM11Result containing the model parameters and predicted/forecasted values.
 */
export function calculateGM11(data: number[], forecastSteps: number = 3): GM11Result | null {
    if (!data || data.length < 4) {
        console.warn("GM(1,1) requires at least 4 data points.");
        return null;
    }

    const n = data.length;

    // 1. Accumulating Generation Operator (AGO)
    const x1: number[] = new Array(n);
    x1[0] = data[0];
    for (let i = 1; i < n; i++) {
        x1[i] = x1[i - 1] + data[i];
    }

    // 2. Mean sequence generated by consecutive neighbors (Z1)
    const z1: number[] = new Array(n - 1);
    for (let i = 1; i < n; i++) {
        z1[i - 1] = 0.5 * x1[i] + 0.5 * x1[i - 1];
    }

    // 3. Formulate matrices B and Y for OLS
    // B = [-z1, 1], Y = [data(2...n)]
    let sumZ = 0;
    let sumZ2 = 0;
    let sumY = 0;
    let sumZY = 0;

    for (let i = 0; i < n - 1; i++) {
        const zVal = -z1[i];
        const yVal = data[i + 1];

        sumZ += zVal;
        sumZ2 += zVal * zVal;
        sumY += yVal;
        sumZY += zVal * yVal;
    }

    const numEquations = n - 1;

    // 4. Calculate parameters a and b using Ordinary Least Squares: u = (B^T * B)^-1 * B^T * Y
    // Matrix B^T * B
    const btb00 = sumZ2;
    const btb01 = sumZ;
    const btb10 = sumZ;
    const btb11 = numEquations;

    const det = (btb00 * btb11) - (btb01 * btb10);
    if (Math.abs(det) < 1e-10) {
        console.warn("GM(1,1) determinant is close to zero, matrix is singular.");
        return null;
    }

    // Inverse of (B^T * B)
    const inv00 = btb11 / det;
    const inv01 = -btb01 / det;
    const inv10 = -btb10 / det;
    const inv11 = btb00 / det;

    // Matrix B^T * Y
    const bty0 = sumZY;
    const bty1 = sumY;

    // u = [a, b]^T
    const a = inv00 * bty0 + inv01 * bty1;
    const b = inv10 * bty0 + inv11 * bty1;

    // 5. Time response function & Inverse AGO
    // x1_hat(k+1) = (data[0] - b/a) * exp(-a*k) + b/a
    // x0_hat(k+1) = x1_hat(k+1) - x1_hat(k)

    const predictedValues: number[] = new Array(n);
    predictedValues[0] = data[0]; // First value is always the same

    const coeff = data[0] - (b / a);

    for (let i = 1; i < n; i++) {
        const x1_k_plus_1 = coeff * Math.exp(-a * i) + (b / a);
        const x1_k = coeff * Math.exp(-a * (i - 1)) + (b / a);
        predictedValues[i] = x1_k_plus_1 - x1_k;
    }

    // 6. Forecasting future values
    const forecast: number[] = [];
    for (let i = n; i < n + forecastSteps; i++) {
        const x1_k_plus_1 = coeff * Math.exp(-a * i) + (b / a);
        const x1_k = coeff * Math.exp(-a * (i - 1)) + (b / a);
        forecast.push(x1_k_plus_1 - x1_k);
    }

    return {
        a,
        b,
        predictedValues,
        forecast
    };
}
